CREATE USER MONATE IDENTIFIED BY PORTFOLIO
DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE VIEW, CREATE SEQUENCE,
CREATE PROCEDURE, CREATE TABLE, CREATE TRIGGER,
CREATE TYPE, CREATE MATERIALIZED VIEW TO MONATE;